### ISSUE TITLE
Flow visualization

### ISSUE THREAD

**Issue by pcmkible** [tldr-group/taufactor#100]
* TauFactor version: 2
* Python version: Anaconda Python 3.7x

### Description

is there a way to visualize "flow"? (e.g. like PoreSpy's "concentration" at the bottom of this page? https://porespy.org/examples/simulations/tutorials/finding_tortuosity_from_image.html)

**Comment by amirDahari1** [comment]
Hi @pcmkible, soon. 

If you want you can pull the development branch and call `s.calc_vertical_flux()` after solve.

**Comment by amirDahari1** [comment]
Solved with #97
