### ISSUE TITLE
Is this version 2 or version 1? 

### ISSUE THREAD

**Issue by pcmkible** [tldr-group/taufactor#101]
is the version I install rightly taufactor 2? I saw your publication https://www.theoj.org/joss-papers/joss.05358/10.21105.joss.05358.pdf linking to this github repo but installing via pip tells me it is taufactor 1.1 so I'm a bit confused

(already have the confirmation from Sam about this but was asked to submit an issue)

**Comment by amirDahari1** [comment]
Hi @pcmkible, yes I see that it's confusing. 

It's taufactor 2 version 1.1.0

(taufactor 1 relates to the Sam's Matlab version)
 
Best,
Amir
