### ISSUE TITLE
dtype padding in surface_area

### ISSUE THREAD

**Issue by amirDahari1** [tldr-group/taufactor#22]
* TauFactor version: 0.1.3

### Description

In surface_area, padding with -1 can be a problem if the dtype of the img is np.uint8 and one of the phases is 255 (-1)

**Comment by isaacsquires** [comment]
Can you explain this more? What is the issue? Is the surface_area calculated wrong? Does it not run? I can't recreate this issue

**Comment by amirDahari1** [comment]
It is calculated wrong. 
The padding should be with a number that is different from all phases.
When padding with -1, it is the same as padding with 255, but 255 is already one of the phases..
