### ISSUE TITLE
Implementation for cuboids

### ISSUE THREAD

**Issue by amirDahari1** [tldr-group/taufactor#24]
* TauFactor version: 0.1.3
* Python version: 3.6.8

### Description

Solving for a cuboid (size 75x140x75) did not converge, while solving for cube did converge.

**Comment by isaacsquires** [comment]
Can you attach the image to this thread as I can't recreate the issue

**Comment by amirDahari1** [comment]
Hmm what do you mean by image?
The output for

`t = s.solve(verbose='per_iter', iter_limit=200000)`

was

'...
199400 6.035706746207325
199500 6.035706746207325
199600 6.035706746207325
199700 6.035706746207325
199800 6.035706746207325
199900 6.035706746207325
200000 6.035706746207325
Did not converge in the iteration limit
converged to: 1.194130246271634 after:  200001 iterations in:  78.5752 seconds at a rate of 0.0004 s/iter`
