### ISSUE TITLE
AttributeError: module 'cupy' has no attribute 'single'

### ISSUE THREAD

**Issue by igennart** [tldr-group/taufactor#61]
* TauFactor version: 0.1.4
* cupy version 11.6.0
* Python version: 3.9.13
* Operating System: Win 10 pro

### Description

I get error by simply importing tau factor : import taufactor as tau

### What I Did

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16224\3374886434.py in <module>
----> 1 import taufactor as tau
      2 

~\anaconda3\lib\site-packages\taufactor\__init__.py in <module>
      5 __version__ = '0.1.4'
      6 
----> 7 from .taufactor import *

~\anaconda3\lib\site-packages\taufactor\taufactor.py in <module>
      7 from taufactor.metrics import surface_area
      8 
----> 9 class Solver:
     10     """
     11     Default solver for two phase images. Once solve method is

~\anaconda3\lib\site-packages\taufactor\taufactor.py in Solver()
     12     called, tau, D_eff and D_rel are available as attributes.
     13     """
---> 14     def __init__(self, img, precision=cp.single, bc=(-0.5, 0.5), D_0=1):
     15         """
     16         Initialise parameters, conc map and other tools that can be re-used

AttributeError: module 'cupy' has no attribute 'single'

**Comment by isaacsquires** [comment]
Hi @igennart, we have just released TauFactor v1.0.0 which no longer uses CuPy. Please try reinstalling. You can find more info here: https://taufactor.readthedocs.io/en/latest/readme.html
