### ISSUE TITLE
Different values for Surface Area Densities and TPB between TauFactor and Avizo3DPro

### ISSUE THREAD

**Issue by therob84** [tldr-group/taufactor#66]
* TauFactor version: 1.5 (Matlab-Installation file via GUI)

### Description

**Surface Area Densities** of my sample data calculated with **TauFactor** differs from calculations made with **Avizo3DPro** "Area3D" module.
**The difference is about 70%.** (for a quite complex sample data with high resolution. I will repeat it with the example data of TauFactor later).
Is this plausible due to different calculation methods?

Description of Area3D-Module in Avizo is quite short ("This module uses "intercepts" to take into account the exposed surface of the outer voxels. The idea being that in the "corners", the contribution of a voxel can vary from 1 to 3 depending on configuration. This measurement is a 3D extension of the Crofton perimeter formula by using 13 intercept directions.")

For TauFactor I read it, for Avizo I am uncertain if the outer voxels of the total volume are excluded from area calculation, or if this could be a source of error.

And the Area "Densitiy" calculation of TauFactor most likely uses the total volume of the data for dividing, not the specific phase volume, right?

**Also TPB-Calculations differ by a factor of 2.**

Although the calculation in Avizo is a little bit manual, I thought it should be correct (Modul "Label Interfaces" with type=3D/Neighbourhood=26voxels/Phases=3) --> Distance Map (Chamfer 3-4-5) --> Module "Thinner" (with Distance Map) --> Trace Lines --> Spatial Graph Statistics

I wonder if I do something wrong in calculations in Avizo, or if it is just the different methods and both should be concidered as "plausible" values, but just not directly comparable?

Hope this question is not to code-off-topic...
Cheers, Robert

**Comment by camsooper** [comment]
Hi Robert,

TauFactor (Matlab) interprets the voxels as little cubes and their square faces as their surfaces. This is different from the Marching Cubes type approach reported in Avizo. Surface area is a thorny issue as for most materials it will be resolution dependant all the way down to the atomic scale, as materials are rough. So, neither method is "right" and each has its advantages: The TF method is very simple and well defined; whereas the Avizo method is a possible a bit more realistic in terms of how it can be scaled with an applied roughness. But should massively underestimate the "true" surface area as measure by BET for example. Same logic appleid to TPB.

Hope this response is clear and somewhat helpful. 

Happy to discuss in more detail over a call. 
Best - Sam

**Comment by therob84** [comment]
Thank you very much for your helpful reply and also your direct contact offer, Sam.

That avizo uses marching cubes is not that well documented, therefore thanks for this information. 

I am also still uncertain which tortuosity factor is best suited to calculate for pore-phase of an water filled fuel/electrolysis cell (PEM or SOEC) using FIB-SEM-data... TauFactor, Avizos XPoreNetwork-Tortuosity, VGStudio hydraulic T. or something completely different? Hm...

Last question: for simplicity I prefer TauFactor GUI via MATLAB (but would have to buy licence first) - and I read [here](https://github.com/tldr-group/taufactor#taufactor-matlab) that matlab version of TauFactor is deprecated, is it true? [Changelog](https://de.mathworks.com/matlabcentral/fileexchange/57956-taufactor#version_history_tab) ends with v1.424 (8 Dec 2022), but inside MATLAB Trial v1.5 is installed... should it be still OK to go with TauFactor via Matlab, or would your suggestion for sure to use Python version (also as Python beginner) for near future? 

Or do you think not so many new developments are integrated in TauFactor anymore and using current version in Matlab should also be fine for near future?

Thanks for reply in advance!
Best, Robert

**Comment by camsooper** [comment]
The MatLab version will live on, but I'm unlikely to add new features to it (unless someone really twists my arm). The python version will be a better bet in the long run, but may never have a GUI. This will be explained in an upcoming TauFactor2 paper. 
For the theory side, feel free to get in touch via email. :)
