### ISSUE TITLE
 Tortuosity of dead-end pore is inconsistent with the npj paper (https://doi.org/10.1038/s41524-020-00386-4)

### ISSUE THREAD

**Issue by LexXU93** [tldr-group/taufactor#76]
* TauFactor version: v1.0.0
* Python version: 3.9.15
* Operating System: RHEL 8.7

### Description
According to figure 3 at "The electrode tortuosity factor: why the conventional tortuosity factor is not well suited for quantifying transport in porous Li-ion battery electrodes and what to use instead", the dead-end pore should not contribute the tortuosity which lead $\tau=inf$. However, we tested taufactor with a few simple 3D cases and get different results.

### What I Did
I create a 50x50x10 plate and create a dead end pore at the center of x-y plan, then solve for both tau and tau_e. 
```
# create plate
solid  = np.zeros((50,50,10))
solid[25,25,:8] = 1
img = torch.permute(torch.tensor(solid), (2,0,1))
flux_direction(img)

# solve for tau
solver = tau.Solver(img)
solver.solve()
print(solver.tau)
print(solver.D_eff)

# solve for tau_e
e_slover = tau.ElectrodeSolver(img)
e_slover.solve()
print(e_slover.tau_e)
print(e_slover.D_eff)
```
I got tau = 0.9143, and tau_e = 0.6568, so I'm wondering why I didn't get inf for tau, also why tau is even higher than tau_e.

Thank you!
Lex

**Comment by stke9** [comment]
see updated tests with deadend pore in the joss review, will be pulled into main soon, thanks so much for pointing this out!

**Comment by LexXU93** [comment]
Thank you for fixing this problem. Great implementation!
