### ISSUE TITLE
JOSS review: Python version >= 3.9 

### ISSUE THREAD

**Issue by ma-sadeghi** [tldr-group/taufactor#77]
NumPy has [dropped support](https://numpy.org/neps/nep-0029-deprecation_policy.html) for Python 3.8 on April 14, 2023. There are some places that unsupport Python versions have been used: `setup.py`, `tox.ini`, etc.

**Comment by stke9** [comment]
Can you elaborate on why this is a problem - users can have compatible versions of python and numpy, we don't necessarily want to force them to use python 3.9 right? I have updated tox to include 3.9 option though!

**Comment by ma-sadeghi** [comment]
I agree that we shouldn't force people to not use unsupported Python versions. It's that unsupported Python/NumPy versions pose potential security risks/bugs that won't be patched. So, it's a good practice to encourage users to use the Python/NumPy versions that are still getting patched. Also, as more libraries drop support for Python 3.8, users may face compatibility issues.

As a side note, it just occured to me that since you've already released v1.0.0, dropping support for unsupported Python/NumPy versions wouldn't affect existing users (since it'll be on the dev branch). Once you make a new release on PyPI, it'll be enforced.

Regarding `setup.py`, could you add Python 3.10 as well? I'm asking because the default Python version on a freshly installed Ubuntu and also the Anaconda Python distribution is 3.10.

**Comment by ma-sadeghi** [comment]
Just to clarify, this is a minor comment, and I'll leave it up you in case you're not convinced :)

**Comment by isaacsquires** [comment]
Hi, we have included 3.9 and 3.10 in our latest release :)
