### ISSUE TITLE
JOSS review: Tolerance used in the speed comparison

### ISSUE THREAD

**Issue by ma-sadeghi** [tldr-group/taufactor#78]
IIRC, TauFactor uses `5e-2` for flux tolerance. Have you made sure that you use an equivalent tolerance for the packages used in the speed comparison chart? I don't know about the rest, but I think PoreSpy uses `1e-8` for "residual" tolerance (might need some trial and error to see how that translates to flux tolerance).

**Comment by stke9** [comment]
It's quite hard to calculate these equivalences, however, we decreased the tolerance on taufactor 2 until the converged value was closer to the 'true' value (calculated with a very low tolerance) than any of the other solvers. Let us know your thoughts on whether this is sufficient.

**Comment by ma-sadeghi** [comment]
In that case, then your actual speedups should be slightly better (when done using an equivalent flux tolerance), which addresses my comment. Thanks!
