### ISSUE TITLE
JOSS review: Tortuosity factor should always be greater than 1?

### ISSUE THREAD

**Issue by ma-sadeghi** [tldr-group/taufactor#79]
In of of the unit tests, tortuosity factor is less than 1. I was under the impression that tortuosity should always be greater than 1. Could you please explain?

https://github.com/tldr-group/taufactor/blob/abd2877ba205badcb24a68b89e76927d8e4e5a14/tests/test_taufactor.py#L318-L328

**Comment by stke9** [comment]
taue, electrode tortuosity, is not always greater than 1, please see https://www.nature.com/articles/s41524-020-00386-4. Thanks!
