### ISSUE TITLE
JOSS review: Some docstrings of the unit tests needs revision

### ISSUE THREAD

**Issue by ma-sadeghi** [tldr-group/taufactor#80]
This is very minor, just for completeness: Could you please revise the docstrings of the unit tests? Some of them don't reflect what the unit test does like:

https://github.com/tldr-group/taufactor/blob/abd2877ba205badcb24a68b89e76927d8e4e5a14/tests/test_taufactor.py#L318-L319

and

https://github.com/tldr-group/taufactor/blob/abd2877ba205badcb24a68b89e76927d8e4e5a14/tests/test_taufactor.py#L330-L331

**Comment by stke9** [comment]
Done and added a few missing, thanks!
