### ISSUE TITLE
JOSS review: Add a unit test for materials with known tortuosity factor

### ISSUE THREAD

**Issue by ma-sadeghi** [tldr-group/taufactor#81]
This is not urgent, but I think it's important: Currently, most of the unit tests (maybe all?) test the edge cases like "tortuosity of open space should be 1" or "tortuosity of a closed space should be infinity", which are indeed required. I think what's missing is to test TauFactor for the cases in between as well, for instance against some idealized shapes with known tortuosity factors (like slanted channels, etc.).

**Comment by stke9** [comment]
Added slanted channel to the tests
