### ISSUE TITLE
Flux field?

### ISSUE THREAD

**Issue by slieblappen** [tldr-group/taufactor#91]
* TauFactor version: 1.0.0
* Python version: 3.10
* Operating System: MacOS Monterey 12.6.7

Hi there, I was wondering if there was a way to pull out the flux field through a 2 phase system to visualize it similar to the total flux map .tif file from the Matlab version of TauFactor.  Or even just the 3d array for the total flux that I could then convert myself to a .tif or visualize it with some other method.  It looks like you have potentially done this already based on the graphic included in the description for the Python version.

_Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen._

I can see that flux is calculated via the concentration gradient as part of the calculation process but I am not sure where to go from there.  My code to calculate tau, d_eff, etc is working well.

Thanks.

**Comment by andtoni** [comment]
Hi Amir,

Thanks for the effort in this module.

I used the code above and it creates a Tensor Object.

May you please advise how to convert this into a file that is suitable for visualization in Paraview? 

How does one convert a Tensor object to a 3D tiff or VTK?

**Comment by amirDahari1** [comment]
Hi @andtoni,

Thanks for reaching out. There are several packages that can handle `.tif` files. I like to use `tifffile`.
You first need to convert the Tensor object into numpy and also to the cpu, so if your Tensor object is `test`, the way to save the file as `.tif` is

`tifffile.imsave("test.tif", test.to("cpu").numpy())`

**Comment by amirDahari1** [comment]
It might be useful to just have a function that saves the flux field as a `.tif` file #97.

**Comment by amirDahari1** [comment]
#97 closed this, you can call s.calc_vertical_flux()
